version: "3.8"

services:

    db:
      image: mariadb:10.5.9
      restart: always
      ports:
        - 3306:3306
      environment:
        MYSQL_ROOT_PASSWORD: exciteroot
        MYSQL_DATABASE: excite_study
        MYSQL_USER: excite
        MYSQL_PASSWORD: excite

    adminer:
      image: adminer:4.8.0
      restart: always
      ports:
        - 8081:8080

    tomcat:
        image: tomcat:10.0.5
        volumes:
        - ./mariadb-java-client-2.7.1.jar:/usr/local/tomcat/lib/mariadb-java-client-2.7.1.jar
        - ./webapps:/usr/local/tomcat/webapps
        ports:
        - 8080:8080
