version: "3.8"

services:

    db:
      image: mariadb:10.5.9
      restart: always
      ports:
        - 3306:3306
      command:
        - mysqld
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      environment:
        MYSQL_ROOT_PASSWORD: exciteroot
        MYSQL_DATABASE: excite_study
        MYSQL_USER: excite
        MYSQL_PASSWORD: excite
      volumes:
        - ./initdb.d:/docker-entrypoint-initdb.d

    adminer:
      image: adminer:4.8.0
      restart: always
      ports:
        - 8081:8080

    tomcat:
        image: tomcat:9.0.45
        environment:
          DB_HOST: db
        volumes:
        - ./mariadb-java-client-2.7.1.jar:/usr/local/tomcat/lib/mariadb-java-client-2.7.1.jar
        - ./webapps:/usr/local/tomcat/webapps
        ports:
        - 8080:8080
